# Site settings
title: Augmented Instruments Laboratory
email: hello@augmentedinstruments.org
description: > # this means to ignore newlines until "baseurl:"
  The Augmented Instruments Laboratory is based at Centre For Digital Music 
  at Queen Mary University of London.
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "localhost:4000"
url: "http://instrumentslab.org" # the base hostname & protocol for your site
twitter_username: instrumentslab
github_username:  instrumentslab
google_analytics: "UA-90171972-1"

# Build settings
markdown: kramdown

exlude: 
  - node_modules

categories:
  - news
  - events

collections: 
  research:
    output: true

sections: 
  - news
  - publications
  - people
  - research
  - contact
  - blog

paginate: 10
paginate_path: "blog/page:num"

plugins:
  - jekyll-redirect-from
