# Site settings
title: Augmented Instruments Laboratory
email: hello@augmentedinstruments.org
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "localhost:4000"
url: "https://disastrid.github.io/instruments_lab/" # the base hostname & protocol for your site
twitter_username: instrumentslab
github_username:  instrumentslab

# Build settings
markdown: kramdown

exlude: 
  - node_modules

categories:
  - news
  - events

collections: 
  research:
    output: true

sections: 
  - news
  - publications
  - people
  - research
  - contact
  - blog

paginate: 10
paginate_path: "blog/page:num"